name: Deploy
on:
  push:
    branches: dev
  pull_request:
    branches: dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DENO_KV_ACCESS_TOKEN: ${{ secrets.DENO_KV_ACCESS_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}


    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check env variables
        run: |
          echo $DENO_KV_ACCESS_TOKEN
          echo $OPENAI_API_KEY
          
      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "smart-todo-manager"
          entrypoint: "main.ts"
          root: "."
